**Задание 1. Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).**

In [1]:
import numpy as np

In [14]:
N = int(input())
N_el = []

while N > 0:
    N -= 1
    N_el.append(N)

x = np.array(N_el)
x

13


array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

**Задание 2. Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.**

In [34]:
import numpy as np

In [46]:
N = int(input())
diag_matrix = np.diag(np.arange(N))

print(diag_matrix)
print ('Сумма диагональных элементов:', sum(diag_matrix.diagonal()))

8
[[0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0]
 [0 0 0 3 0 0 0 0]
 [0 0 0 0 4 0 0 0]
 [0 0 0 0 0 5 0 0]
 [0 0 0 0 0 0 6 0]
 [0 0 0 0 0 0 0 7]]
Сумма диагональных элементов: 28


**Задание 3. Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.**

In [49]:
import pandas as pd

Скачиваем ml-latest-small.zip.

In [59]:
data = pd.read_csv('ml-latest-small/ratings.csv')
high_rating = data [ (data['rating'] == 5.0)]
best_film = high_rating.groupby('movieId').count().sort_values('userId', ascending = False).head(1)
best_film

userId  rating  timestamp
movieId                           
318         153     153        153